server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name 195.209.210.68;
    ssl_certificate /etc/letsencrypt/live/195.209.210.68/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/195.209.210.68/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:ALFATLS:10m;
    ssl_session_timeout 1d;

    access_log off;
    error_log /dev/null crit;
    server_tokens off;
    client_max_body_size 8000000;
    client_body_timeout 15s;

    location / {
        proxy_pass http://127.0.0.1:8091;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_connect_timeout 2s;
        proxy_send_timeout 12s;
        proxy_read_timeout 12s;
        proxy_buffering off;
    }
}
